// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLESSTransport.DAL;

namespace QLESSTransport.API.Migrations
{
    [DbContext(typeof(QLESSContext))]
    partial class QLESSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.QLESSTransport.Models.Entities.MrtFare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fare")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MrtFares");
                });

            modelBuilder.Entity("QLESSTransport.Models.TransportCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountAppliedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountRegistrationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Load")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportCardType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransportCards");
                });
#pragma warning restore 612, 618
        }
    }
}
